# Generated by Django 4.2.7 on 2025-12-13 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_groupmessage_is_read_userprofile_notification_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="New Chat", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "User"), ("ai", "AI")], max_length=10
                    ),
                ),
                ("message_text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.aichat",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="pinnedchat",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="pinnedchat",
            name="group",
        ),
        migrations.RemoveField(
            model_name="pinnedchat",
            name="private_user",
        ),
        migrations.RemoveField(
            model_name="pinnedchat",
            name="user",
        ),
        migrations.RemoveField(
            model_name="groupmessage",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="notification_count",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="theme",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="PinnedChat",
        ),
        migrations.AddIndex(
            model_name="aichatmessage",
            index=models.Index(
                fields=["chat", "timestamp"], name="chat_aichat_chat_id_06096e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichat",
            index=models.Index(
                fields=["user", "-updated_at"], name="chat_aichat_user_id_a37e8a_idx"
            ),
        ),
    ]
