# Generated by Django 4.2.7 on 2025-12-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_aichat_aichatmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_delivered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
