# Generated by Django 4.2.7 on 2025-12-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_add_message_delivery_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
